/// Flutter icons GardenPlannerIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GardenPlannerIcons
///      fonts:
///       - asset: fonts/GardenPlannerIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GardenPlannerIcons {
  GardenPlannerIcons._();

  static const _kFontFam = 'GardenPlannerIcons';
  static const _kFontPkg = null;

  static const IconData floppy = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tribes = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guides = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData growveg = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yearbook = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData previous = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plants = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planting = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watering = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData care = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pests = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData harvesting = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain_1 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plans = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mulching = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weeding = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plansalt = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_dir = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_dir = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_waxing_crescent = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasks = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData digging = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fertilising = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_day = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_night = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudy = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fog = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_first_quarter = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_full = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_last_quarter = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData partly_cloudy_day = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData partly_cloudy_night = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sleet = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature_down_arrow = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature_up_arrow = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_moon = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_waning_gibbous = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_waning_crescent = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_waxing_gibbous = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xf0c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_cloud = IconData(0xf0ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinner = IconData(0xf110, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention_alt = IconData(0xf12a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xf12b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_circle_o = IconData(0xf2be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
